export { default as s00 } from "./00-Intro.mdx";
export { default as s01 } from "./01-Agile Development Practices.mdx";
export { default as s02 } from "./02-Design and Architecture - Project Description.mdx";
export { default as s03 } from "./03-Design and Architecture - Role.mdx";
export { default as s04 } from "./04-Design and Architecture - Code Structure Before.mdx";
export { default as s05 } from "./05-Design and Architecture - Code Structure After.mdx";
export { default as s06 } from "./06-Design and Architecture - Request Lifecycle Before.mdx";
export { default as s07 } from "./07-Design and Architecture - Request Lifecycle After.mdx";
export { default as s08 } from "./08-Learning and Continuous Improvement.mdx";
export { default as s09 } from "./09-Line Management and Coaching.mdx";
export { default as s10 } from "./10-Break.mdx";
export { default as s11 } from "./11-Conflict Resolution.mdx";
export { default as s12 } from "./12-Planning and Organisation.mdx";
export { default as s13 } from "./13-Stakeholder Management.mdx";
export { default as s14 } from "./14-Diversity and Inclusion.mdx";
export { default as s15 } from "./15-Questions.mdx";
